/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ColorPicker: typeof import('./src/components/ColorPicker.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IPadAir: typeof import('./src/components/IPadAir.vue')['default']
    IPhoneX: typeof import('./src/components/IPhoneX.vue')['default']
    MacBook: typeof import('./src/components/MacBook.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screenshot: typeof import('./src/components/Screenshot.vue')['default']
    TButton: typeof import('tdesign-vue-next')['Button']
    TColorPicker: typeof import('tdesign-vue-next')['ColorPicker']
    TContent: typeof import('tdesign-vue-next')['Content']
    THeader: typeof import('tdesign-vue-next')['Header']
    THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
    TInput: typeof import('tdesign-vue-next')['Input']
    TLayout: typeof import('tdesign-vue-next')['Layout']
  }
}
